export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const CHANGE_EMAIL_SIGNIN = 'CHANGE_EMAIL_SIGNIN'
export const CHANGE_PASSWORD_SIGNIN = 'CHANGE_PASSWORD_SIGNIN'

export const SIGNIN_PENDING = 'SIGNIN_PENDING'
export const SIGNIN_FAILED  = 'SIGNIN_FAILED'