export const CHANGE_NAME_REG = 'CHANGE_NAME_REG'
export const CHANGE_EMAIL_REG = 'CHANGE_EMAIL_REG'
export const CHANGE_PASSWORD_REG = 'CHANGE_PASSWORD_REG'

export const REGISTER_PENDING = 'REGISTER_PENDING'
export const REGISTER_FAILED  = 'REGISTER_FAILED'