export const CHANGE_URL_INPUT = 'CHANGE_URL_INPUT'

export const CHANGE_ROUTE = 'CHANGE_ROUTE'

export const SIGNIN_SUCCESS_LOAD_USER = 'SIGNIN_SUCCESS_LOAD_USER'

export const PREDICT_FACE_PENDING = 'PREDICT_FACE_PENDING'
export const PREDICT_FACE_SUCCESS = 'PREDICT_FACE_SUCCESS'
export const PREDICT_FACE_FAILED  = 'PREDICT_FACE_FAILED'

export const UPDATE_SUBMISSION_PENDING = 'UPDATE_SUBMISSION_PENDING'
export const UPDATE_SUBMISSION_SUCCESS = 'UPDATE_SUBMISSION_SUCCESS'
export const UPDATE_SUBMISSION_FAILED  = 'UPDATE_SUBMISSION_FAILED'

export const FACE_MARKINGS = 'FACE_MARKINGS'
export const NO_FACE_MARKINGS = 'NO_FACE_MARKINGS'
export const CLEAR_MARKINGS = 'CLEAR_MARKINGS'